### ISSUE TITLE
Vi que ta fazendo o curso de Git e GitHub

### ISSUE THREAD

**Issue by Carlos7045** [keytoncunha/git_github#1]
To iniciando a pouco tempo no mundo de programação, ja fiz o curso de Python do Curso em Video entre outros...
Me chama la no Whatsapp se tiver interesse em trocar experiencias ou estudar juntos, estou estudando sozinho sem ter niguem pra conversar sobre... Meu Whatsapp: 63 99944-7870

**Comment by keytoncunha** [comment]
@Carlos7045  Estou focado em front end.  :page_with_curl:

**Comment by Carlos7045** [comment]
Eu entrei no nesse mundo atravez de Python, mas atualmente estudo HTML, CSS, JS e PHP, esse é meu foco para me aprimorar e conseguir entrar no mercado de trabalho, mas meu plano a longo prazo é entrar no mundo de IA
